// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// InviteUserDao is the data access object for table invite_user.
type InviteUserDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns InviteUserColumns // columns contains all the column names of Table for convenient usage.
}

// InviteUserColumns defines and stores column names for table invite_user.
type InviteUserColumns struct {
	Id       string //
	UserId   string // 用户id
	InviteId string // 邀请id
	IsDelete string //
}

// inviteUserColumns holds the columns for table invite_user.
var inviteUserColumns = InviteUserColumns{
	Id:       "id",
	UserId:   "user_id",
	InviteId: "invite_id",
	IsDelete: "is_delete",
}

// NewInviteUserDao creates and returns a new DAO object for table data access.
func NewInviteUserDao() *InviteUserDao {
	return &InviteUserDao{
		group:   "default",
		table:   "invite_user",
		columns: inviteUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *InviteUserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *InviteUserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *InviteUserDao) Columns() InviteUserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *InviteUserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *InviteUserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *InviteUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
