
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # 工具编译配置
  build:
    name:     "focus"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test_love"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true