// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// InviteUser is the golang structure of table invite_user for DAO operations like Where/Data.
type InviteUser struct {
	g.Meta   `orm:"table:invite_user, do:true"`
	Id       interface{} //
	UserId   interface{} // 用户id
	InviteId interface{} // 邀请id
	IsDelete interface{} //
}
