// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Invite is the golang structure of table invite for DAO operations like Where/Data.
type Invite struct {
	g.Meta     `orm:"table:invite, do:true"`
	Id         interface{} //
	InviteId   interface{} // 邀请ID
	InviteCode interface{} // 邀请码
	InviteType interface{} // 邀请方式 1-私密邀请
	IsDelete   interface{} //
}
