// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Note is the golang structure of table note for DAO operations like Where/Data.
type Note struct {
	g.Meta     `orm:"table:note, do:true"`
	Id         interface{} //
	NoteId     interface{} // 文章id
	UserId     interface{} // 用户ID
	Content    interface{} // 内容
	Status     interface{} // 状态 0-生效中 1-已完成
	NoteType   interface{} // 心愿类型 1-想要的礼物 2-想做的事情
	IsDelete   interface{} //
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
}
