// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "server/internal/logic/bizctx"
	_ "server/internal/logic/session"
	_ "server/internal/logic/user"
)
