# HTTP Server.
server:
  address: ":8020"
  dumpRouterMap: true
  routeOverWrite: true
  accessLogEnabled: true
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# Database.
database:
  logger:
    path:    "logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test_love"
    debug: true

# 文件上传设置
upload:
  path: "upload"

# Logger configurations.
logger:
  path:    "logs/default"
  level:   "all"
  stdout:  true
  ctxKeys: ["RequestId"]