// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalInviteDao is internal type for wrapping internal DAO implements.
type internalInviteDao = *internal.InviteDao

// inviteDao is the data access object for table invite.
// You can define custom methods on it to extend its functionality as you wish.
type inviteDao struct {
	internalInviteDao
}

var (
	// Invite is globally public accessible object for table invite operations.
	Invite = inviteDao{
		internal.NewInviteDao(),
	}
)

// Fill with you ideas below.
