// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Invite is the golang structure for table invite.
type Invite struct {
	Id         int64  `json:"id"         description:""`
	InviteId   int64  `json:"inviteId"   description:"邀请ID"`
	InviteCode string `json:"inviteCode" description:"邀请码"`
	InviteType int    `json:"inviteType" description:"邀请方式 1-私密邀请"`
	IsDelete   bool   `json:"isDelete"   description:""`
}
