// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"server/internal/model"
	"server/internal/model/entity"
)

type (
	IInvite interface {
		CreateInvite(ctx context.Context, in model.InviteCreateInput) (err error)
		QueryInvite(ctx context.Context) (list []*entity.Invite, err error)
		InviteUser(ctx context.Context, in model.InviteUserInput) (err error)
	}
)

var (
	localInvite IInvite
)

func Invite() IInvite {
	if localInvite == nil {
		panic("implement not found for interface IInvite, forgot register?")
	}
	return localInvite
}

func RegisterInvite(i IInvite) {
	localInvite = i
}
