// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"server/internal/model"
	"server/internal/model/entity"
)

type (
	INote interface {
		CreateNote(ctx context.Context, in model.NoteCreateInput) (err error)
		QueryNote(ctx context.Context, query *model.NoteQuery) (list []*entity.Note, err error)
	}
)

var (
	localNote INote
)

func Note() INote {
	if localNote == nil {
		panic("implement not found for interface INote, forgot register?")
	}
	return localNote
}

func RegisterNote(i INote) {
	localNote = i
}
